-- Church name/visibility hygiene fixes -- generated by
-- scripts/church-name-hygiene.js against the live database.
-- Review every statement below before running any of it.

-- ===================================================================
-- 1) HIDE: names indicating an IRS-extract "nonprofit" artifact, not a
--    real congregation display name. Reversible (is_hidden = true),
--    same column search_churches/search_events already filter on.
-- ===================================================================

-- Life Change Church of San Antonio Tx a Domestic Nonprofit Corp
UPDATE churches SET is_hidden = true WHERE id = 'deddcbf5-31a5-447e-aeac-902e82afb15c' AND name = 'Life Change Church of San Antonio Tx a Domestic Nonprofit Corp';

-- ===================================================================
-- 2) FIX: locator-suffix strip + TX/acronym casing. REVIEW EACH ONE --
--    the suffix regex can't always tell a real city from a ministry
--    descriptor after a dash. Delete any line that looks wrong before
--    running this file.
-- ===================================================================

-- Life Community Church Sa Inc  ->  Life Community Church SA Inc
UPDATE churches SET name = 'Life Community Church SA Inc' WHERE id = '055b545b-5455-4207-876e-6f02e747a6e0' AND name = 'Life Community Church Sa Inc';

-- Pursuit Church Sa  ->  Pursuit Church SA
UPDATE churches SET name = 'Pursuit Church SA' WHERE id = '06e8d4b0-6424-459d-b9e3-72af86afb11b' AND name = 'Pursuit Church Sa';

-- Church At Boerne  ->  Church at Boerne
UPDATE churches SET name = 'Church at Boerne' WHERE id = '2a0db37c-7871-4e4d-8198-8322b3c232fd' AND name = 'Church At Boerne';

-- Genesis Church Of San Antonio  ->  Genesis Church of San Antonio
UPDATE churches SET name = 'Genesis Church of San Antonio' WHERE id = '2c8b0008-a2ad-4a7d-8bc1-b16d862d0f7f' AND name = 'Genesis Church Of San Antonio';

-- Metro Church Sa Inc  ->  Metro Church SA Inc
UPDATE churches SET name = 'Metro Church SA Inc' WHERE id = '2faf580a-24a2-489e-afc6-c6a5cbf481c5' AND name = 'Metro Church Sa Inc';

-- Christian Fellowship Church Of  ->  Christian Fellowship Church of
UPDATE churches SET name = 'Christian Fellowship Church of' WHERE id = '33deedc5-7445-45d2-b209-92e60965fc58' AND name = 'Christian Fellowship Church Of';

-- New Braunfels Central Tx Foursquare Church  ->  New Braunfels Central TX Foursquare Church
UPDATE churches SET name = 'New Braunfels Central TX Foursquare Church' WHERE id = '41b92f5d-b1a3-4413-b7ef-5cf46672631a' AND name = 'New Braunfels Central Tx Foursquare Church';

-- Sa Basic Ministries Inc  ->  SA Basic Ministries Inc
UPDATE churches SET name = 'SA Basic Ministries Inc' WHERE id = '4a5b89fd-f28d-48ad-9a70-bcac42187fdd' AND name = 'Sa Basic Ministries Inc';

-- The Oasis At Faith Worship Center San Antonio Inc  ->  The Oasis at Faith Worship Center San Antonio Inc
UPDATE churches SET name = 'The Oasis at Faith Worship Center San Antonio Inc' WHERE id = '4b35de7f-5dd1-45fa-8fe0-6a2332006831' AND name = 'The Oasis At Faith Worship Center San Antonio Inc';

-- Redemption Church Sa  ->  Redemption Church SA
UPDATE churches SET name = 'Redemption Church SA' WHERE id = '4bcb35a1-e46b-486e-a921-5feb5433a71d' AND name = 'Redemption Church Sa';

-- Refuge Church At Lone Star  ->  Refuge Church at Lone Star
UPDATE churches SET name = 'Refuge Church at Lone Star' WHERE id = '5546fd8a-f076-4497-8b15-8d8a2698fc62' AND name = 'Refuge Church At Lone Star';

-- 360 Inner City Church - San Antonio Tx  ->  360 Inner City Church
UPDATE churches SET name = '360 Inner City Church' WHERE id = '67abfc19-a3f6-48bd-97ea-07dcc02e4848' AND name = '360 Inner City Church - San Antonio Tx';

-- Anchored Ministries Sa  ->  Anchored Ministries SA
UPDATE churches SET name = 'Anchored Ministries SA' WHERE id = '79e5d37a-3482-4a4f-9c58-240c179a26a6' AND name = 'Anchored Ministries Sa';

-- All Nations Church-Onnuri At San Antonio  ->  All Nations Church-Onnuri at San Antonio
UPDATE churches SET name = 'All Nations Church-Onnuri at San Antonio' WHERE id = '8d61444d-6a6f-468f-9b9b-0858ba54e3d9' AND name = 'All Nations Church-Onnuri At San Antonio';

-- Church of the Firstborn Sa  ->  Church of the Firstborn SA
UPDATE churches SET name = 'Church of the Firstborn SA' WHERE id = '915f89e8-7273-4f4c-8d8b-5b6debe55d39' AND name = 'Church of the Firstborn Sa';

-- Crossbridge Community Church Of San Antonio  ->  Crossbridge Community Church of San Antonio
UPDATE churches SET name = 'Crossbridge Community Church of San Antonio' WHERE id = '980e3784-ea9d-4c2a-924c-91c6ab03c791' AND name = 'Crossbridge Community Church Of San Antonio';

-- Gospel Of Truth Church Of The Living God International Inc  ->  Gospel of Truth Church of The Living God International Inc
UPDATE churches SET name = 'Gospel of Truth Church of The Living God International Inc' WHERE id = '98dce2ee-078a-4b75-b1f1-de5852755094' AND name = 'Gospel Of Truth Church Of The Living God International Inc';

-- Fresh Oil Ministries of San Antonio Tx Inc  ->  Fresh Oil Ministries of San Antonio TX Inc
UPDATE churches SET name = 'Fresh Oil Ministries of San Antonio TX Inc' WHERE id = '9bdd5ec5-02aa-4fa0-95c7-a149e138ec86' AND name = 'Fresh Oil Ministries of San Antonio Tx Inc';

-- Church At Faith Walk Fellowship  ->  Church at Faith Walk Fellowship
UPDATE churches SET name = 'Church at Faith Walk Fellowship' WHERE id = 'c04b7c31-cbc9-40fe-a779-29b79779af69' AND name = 'Church At Faith Walk Fellowship';

-- Church of Christ At New Braunfels  ->  Church of Christ at New Braunfels
UPDATE churches SET name = 'Church of Christ at New Braunfels' WHERE id = 'c070fa3e-bacf-44d2-91af-55ba5695c965' AND name = 'Church of Christ At New Braunfels';

-- Servants Of Servants Ministries  ->  Servants of Servants Ministries
UPDATE churches SET name = 'Servants of Servants Ministries' WHERE id = 'd6903d47-00f3-48a6-9d35-e0c7ef3704f5' AND name = 'Servants Of Servants Ministries';

-- Issues Of Life Ministrys  ->  Issues of Life Ministrys
UPDATE churches SET name = 'Issues of Life Ministrys' WHERE id = 'e28a61bd-dee3-44fd-b0a1-4a010d15326b' AND name = 'Issues Of Life Ministrys';

-- Church At Vineyard Hills  ->  Church at Vineyard Hills
UPDATE churches SET name = 'Church at Vineyard Hills' WHERE id = 'e6609915-9632-4350-879a-29e0570da517' AND name = 'Church At Vineyard Hills';

-- El Camino Christian Church Tx Inc  ->  El Camino Christian Church TX Inc
UPDATE churches SET name = 'El Camino Christian Church TX Inc' WHERE id = 'eed45544-29f6-4a83-9c71-a10d68b8aa7f' AND name = 'El Camino Christian Church Tx Inc';

-- San Antonio Church of Christ At Viewcrest  ->  San Antonio Church of Christ at Viewcrest
UPDATE churches SET name = 'San Antonio Church of Christ at Viewcrest' WHERE id = 'f88f0bc5-7215-4809-8dda-b69b2a25fd3b' AND name = 'San Antonio Church of Christ At Viewcrest';

-- ===================================================================
-- 3) FLAGGED, NOT AUTO-FIXABLE: name still ends in "of"/"at" with
--    nothing after it (after the fixes above) -- looks like an import
--    that lost its trailing city/descriptor. No SQL generated for
--    these -- go find the actual full name and fix by hand.
-- ===================================================================

-- id 33deedc5-7445-45d2-b209-92e60965fc58: "Christian Fellowship Church Of"
