-- Follow-up batch to san_antonio_metro_churches.fix_acronym_casing.sql
-- (already run) -- catches "Tx" title-cased instead of kept "TX",
-- now that TX was added to ACRONYM_EXCEPTIONS in
-- scripts/acronym-exceptions.js. Generated by that script against the
-- live database; reported live via a church card showing "New
-- Braunfels Central Tx Foursquare Church".

-- New Braunfels Central Tx Foursquare Church  ->  New Braunfels Central TX Foursquare Church
UPDATE churches SET name = 'New Braunfels Central TX Foursquare Church' WHERE id = '41b92f5d-b1a3-4413-b7ef-5cf46672631a' AND name = 'New Braunfels Central Tx Foursquare Church';

-- 360 Inner City Church - San Antonio Tx  ->  360 Inner City Church - San Antonio TX
UPDATE churches SET name = '360 Inner City Church - San Antonio TX' WHERE id = '67abfc19-a3f6-48bd-97ea-07dcc02e4848' AND name = '360 Inner City Church - San Antonio Tx';

-- Fresh Oil Ministries of San Antonio Tx Inc  ->  Fresh Oil Ministries of San Antonio TX Inc
UPDATE churches SET name = 'Fresh Oil Ministries of San Antonio TX Inc' WHERE id = '9bdd5ec5-02aa-4fa0-95c7-a149e138ec86' AND name = 'Fresh Oil Ministries of San Antonio Tx Inc';

-- Life Change Church of San Antonio Tx a Domestic Nonprofit Corp  ->  Life Change Church of San Antonio TX a Domestic Nonprofit Corp
UPDATE churches SET name = 'Life Change Church of San Antonio TX a Domestic Nonprofit Corp' WHERE id = 'deddcbf5-31a5-447e-aeac-902e82afb15c' AND name = 'Life Change Church of San Antonio Tx a Domestic Nonprofit Corp';

-- El Camino Christian Church Tx Inc  ->  El Camino Christian Church TX Inc
UPDATE churches SET name = 'El Camino Christian Church TX Inc' WHERE id = 'eed45544-29f6-4a83-9c71-a10d68b8aa7f' AND name = 'El Camino Christian Church Tx Inc';
