-- Corrects church names where a known acronym (SATX, RGV, UPCI, UMC, EFCA, SBC, COGIC, AME, ELCA, PCA, AG)
-- was title-cased instead of kept all-caps -- generated by
-- scripts/acronym-exceptions.js against the live database.
-- Extend ACRONYM_EXCEPTIONS in that file and re-run to catch more.

-- River Church Rgv Inc  ->  River Church RGV Inc
UPDATE churches SET name = 'River Church RGV Inc' WHERE id = '01335b3e-8d81-4ae7-9fbe-427eefe28fee' AND name = 'River Church Rgv Inc';

-- Christ Community Church Satx  ->  Christ Community Church SATX
UPDATE churches SET name = 'Christ Community Church SATX' WHERE id = '16d011ca-f1c3-48ff-b07d-304050a7c2a9' AND name = 'Christ Community Church Satx';

-- The Church Upci Inc  ->  The Church UPCI Inc
UPDATE churches SET name = 'The Church UPCI Inc' WHERE id = '1ae1b8ab-c68f-4e30-815f-2b57fcb2ae7d' AND name = 'The Church Upci Inc';

-- Waypoint Church Satx  ->  Waypoint Church SATX
UPDATE churches SET name = 'Waypoint Church SATX' WHERE id = '3ead921c-aaaa-40f0-9164-c870c845acec' AND name = 'Waypoint Church Satx';

-- Windsong Christian Center Umc  ->  Windsong Christian Center UMC
UPDATE churches SET name = 'Windsong Christian Center UMC' WHERE id = '734ee125-966b-4004-a08b-8268cb4c1e29' AND name = 'Windsong Christian Center Umc';

-- Redeemed Ministries Satx  ->  Redeemed Ministries SATX
UPDATE churches SET name = 'Redeemed Ministries SATX' WHERE id = '7ddded93-65bd-44c6-ac3e-9e9b6f521393' AND name = 'Redeemed Ministries Satx';

-- Christ Church Pca of San Antonio  ->  Christ Church PCA of San Antonio
UPDATE churches SET name = 'Christ Church PCA of San Antonio' WHERE id = '8e8c576d-47d5-4d39-bb9c-7a857a332e1a' AND name = 'Christ Church Pca of San Antonio';

-- Mission Community Church- Efca  ->  Mission Community Church- EFCA
UPDATE churches SET name = 'Mission Community Church- EFCA' WHERE id = 'd3050639-b5f5-4c0d-9dc6-83ee0992885d' AND name = 'Mission Community Church- Efca';

-- Sherman Chapel Ame Church  ->  Sherman Chapel AME Church
UPDATE churches SET name = 'Sherman Chapel AME Church' WHERE id = 'e5c512b0-85ae-4a80-862d-f9c92d6127a0' AND name = 'Sherman Chapel Ame Church';
